export const ACCOUNT_LOGIN_DATA_NOT_PROVIDED = 'ACCOUNT_LOGIN_DATA_NOT_PROVIDED';
export const ACCOUNT_LOGIN_ID_NOT_PROVIDED = 'ACCOUNT_LOGIN_ID_NOT_PROVIDED';
export const ACCOUNT_LOGIN_NOT_FOUND = 'ACCOUNT_LOGIN_NOT_FOUND';
export const ACCOUNT_LOGIN_PASSWORD_LENGTH_3_30 = 'ACCOUNT_LOGIN_PASSWORD_LENGTH_3_30';
export const ACCOUNT_LOGIN_PASSWORD_REQUIRED = 'ACCOUNT_LOGIN_PASSWORD_REQUIRED';
export const ACCOUNT_LOGIN_USERNAME_LENGTH_3_30 = 'ACCOUNT_LOGIN_USERNAME_LENGTH_3_30';
export const ACCOUNT_LOGIN_USERNAME_REQUIRED = 'ACCOUNT_LOGIN_USERNAME_REQUIRED';
