export const CART_DATA_NOT_PROVIDED = 'CART_DATA_NOT_PROVIDED';
export const CART_ID_NOT_PROVIDED = 'CART_ID_NOT_PROVIDED';
export const CART_ITEMS_REQUIRED = 'CART_ITEMS_REQUIRED';
export const CART_NOT_FOUND = 'CART_NOT_FOUND';
export const CART_USER_ID_REQUIRED = 'CART_USER_ID_REQUIRED';
