export const CART_ITEM_DATA_NOT_PROVIDED = 'CART_ITEM_DATA_NOT_PROVIDED';
export const CART_ITEM_ID_NOT_PROVIDED = 'CART_ITEM_ID_NOT_PROVIDED';
export const CART_ITEM_NOT_FOUND = 'CART_ITEM_NOT_FOUND';
export const CART_ITEM_PRODUCT_ID_REQUIRED = 'CART_ITEM_PRODUCT_ID_REQUIRED';
export const CART_ITEM_QUANTITY_IS_POSITIVE = 'CART_ITEM_QUANTITY_IS_POSITIVE';
export const CART_ITEM_QUANTITY_MAX = 'CART_ITEM_QUANTITY_MAX';
export const CART_ITEM_QUANTITY_MIN = 'CART_ITEM_QUANTITY_MIN';
export const CART_ITEM_QUANTITY_REQUIRED = 'CART_ITEM_QUANTITY_REQUIRED';
