export const COMMENT_DATA_NOT_PROVIDED = 'COMMENT_DATA_NOT_PROVIDED';
export const COMMENT_ID_NOT_PROVIDED = 'COMMENT_ID_NOT_PROVIDED';
export const COMMENT_MESSAGE_LENGTH_10_5000 = 'COMMENT_MESSAGE_LENGTH_10_5000';
export const COMMENT_MESSAGE_REQUIRED = 'COMMENT_MESSAGE_REQUIRED';
export const COMMENT_NOT_FOUND = 'COMMENT_NOT_FOUND';
