export const PRODUCT_DATA_NOT_PROVIDED = 'PRODUCT_DATA_NOT_PROVIDED';
export const PRODUCT_ID_NOT_PROVIDED = 'PRODUCT_ID_NOT_PROVIDED';
export const PRODUCT_NOT_FOUND = 'PRODUCT_NOT_FOUND';
export const PRODUCT_PRICE_IS_POSITIVE = 'PRODUCT_PRICE_IS_POSITIVE';
export const PRODUCT_PRICE_REQUIRED = 'PRODUCT_PRICE_REQUIRED';
export const PRODUCT_TITLE_LENGTH_10_80 = 'PRODUCT_TITLE_LENGTH_10_80';
export const PRODUCT_TITLE_REQUIRED = 'PRODUCT_TITLE_REQUIRED';
