version: "3"
services:
  mongodatabasedocker:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    ports:
      - 27017:27017
    volumes:
      - ../../../.volumes/mongodatabasedocker:/data/db:rw
  mongodatabasedocker-migrations:
    build:
      context: ../../../
      dockerfile: environments/local/services/mongodatabasedocker/migrations/Dockerfile
    image: mongo-migrations
    volumes:
      - ../../../node_modules:/app/node_modules:rw
    links:
      - mongodatabasedocker:mongo
  apidocker:
    build:
      context: ../../../
      dockerfile: environments/local/services/apidocker/Dockerfile
    image: serverless
    volumes:
      - ../../../:/app:rw
      - ../../../node_modules:/app/node_modules:rw
    ports:
      - 3010:3000
    links:
      - mongodatabasedocker
      - mongodatabasedocker-migrations
  mongoexpressdocker:
    image: mongo-express
    restart: always
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root
    ports:
      - 8081:8081 
    links:
      - mongodatabasedocker:mongo
